import { $ } from "bun";
import { WorktreeError } from "./errors";

const TREES_DIR = ".workstreams/trees";

export class WorktreeManager {
  async create(name: string, baseBranch?: string): Promise<string> {
    const branch = `ws/${name}`;
    const path = `${TREES_DIR}/${name}`;
    const base = baseBranch ?? "HEAD";
    const { rm } = await import("fs/promises");

    // If no explicit base branch, check HEAD is valid (fails on repos with no commits)
    if (!baseBranch) {
      const headValid = await $`git rev-parse HEAD`.quiet().then(() => true).catch(() => false);
      if (!headValid) {
        console.log("No commits found — creating an empty initial commit...");
        await $`git commit --allow-empty -m "initial commit"`.quiet();
      }
    }

    // Clean up any stale state from a previous run to make creation idempotent
    await $`git worktree remove ${path} --force`.quiet().catch(() => {});
    await rm(path, { recursive: true, force: true });
    await $`git branch -D ${branch}`.quiet().catch(() => {});

    try {
      await $`git worktree add -b ${branch} ${path} ${base}`.quiet();
    } catch (e: any) {
      throw new WorktreeError(
        `Failed to create worktree for "${name}": ${e.stderr?.toString() ?? e.message}`
      );
    }

    // Write a Claude Code pre-tool hook into the worktree that blocks any
    // Read/Edit/Write targeting files outside this worktree.  This prevents
    // agents (and interactive Claude sessions) from accidentally modifying the
    // main repo or other worktrees.
    await this.writeWorktreeGuard(path);

    return path;
  }

  private async writeWorktreeGuard(worktreePath: string): Promise<void> {
    const { mkdir, writeFile, chmod } = await import("fs/promises");
    const { resolve } = await import("path");
    const absPath = resolve(worktreePath);

    // Guard script: receives tool input JSON on stdin, rejects file paths outside worktree
    const guardScript = `#!/bin/bash
# Auto-generated by ws — blocks file access outside this worktree
WORKTREE="${absPath}"
INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | grep -o '"file_path":"[^"]*"' | head -1 | sed 's/"file_path":"\\(.*\\)"/\\1/')
if [ -z "$FILE_PATH" ]; then
  exit 0
fi
# Resolve the path
RESOLVED=$(cd "$WORKTREE" && realpath -m "$FILE_PATH" 2>/dev/null || echo "$FILE_PATH")
case "$RESOLVED" in
  "$WORKTREE"/*)
    exit 0
    ;;
  *)
    echo "BLOCKED: file_path \\"$FILE_PATH\\" is outside this worktree ($WORKTREE). Use relative paths or paths under the worktree." >&2
    exit 2
    ;;
esac
`;

    const claudeDir = `${worktreePath}/.claude`;
    await mkdir(claudeDir, { recursive: true });
    const scriptPath = `${claudeDir}/worktree-guard.sh`;
    await writeFile(scriptPath, guardScript);
    await chmod(scriptPath, 0o755);

    const settings = {
      hooks: {
        PreToolUse: [
          {
            matcher: "Edit|Write|Read",
            hooks: [
              {
                type: "command",
                command: `${resolve(scriptPath)}`,
              },
            ],
          },
        ],
      },
    };

    await writeFile(
      `${claudeDir}/settings.local.json`,
      JSON.stringify(settings, null, 2) + "\n",
    );
  }

  async remove(name: string): Promise<void> {
    const path = `${TREES_DIR}/${name}`;
    const branch = `ws/${name}`;
    const { rm } = await import("fs/promises");

    await $`git worktree remove ${path} --force`.quiet().catch(() => {});
    await rm(path, { recursive: true, force: true });
    await $`git branch -D ${branch}`.quiet().catch(() => {});
  }

  async list(): Promise<Array<{ path: string; branch: string; head: string }>> {
    const result = await $`git worktree list --porcelain`.quiet();
    const output = result.stdout.toString();
    const entries: Array<{ path: string; branch: string; head: string }> = [];
    let current: Partial<{ path: string; branch: string; head: string }> = {};

    for (const line of output.split("\n")) {
      if (line.startsWith("worktree ")) {
        if (current.path) entries.push(current as any);
        current = { path: line.slice(9) };
      } else if (line.startsWith("HEAD ")) {
        current.head = line.slice(5);
      } else if (line.startsWith("branch ")) {
        current.branch = line.slice(7).replace("refs/heads/", "");
      }
    }
    if (current.path) entries.push(current as any);
    return entries;
  }

  async diff(name: string): Promise<string> {
    const path = `${TREES_DIR}/${name}`;
    const result = await $`git -C ${path} diff HEAD`.quiet();
    return result.stdout.toString();
  }

  async diffBranch(branch: string, baseBranch?: string): Promise<string> {
    const base = baseBranch ?? "HEAD";
    const result = await $`git diff ${base}...${branch}`.quiet();
    return result.stdout.toString();
  }
}
